version: '3.8'

services:
  frontend-test:
    build:
      context: ./frontend
      target: dependencies
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=test
    command: npm test
