version: '3.8'

services:
  # Development and testing environment
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
      - /app/frontend/node_modules
    environment:
      - NODE_ENV=development
      - HUSKY=0  # Disable git hooks
    healthcheck:
      test: ["CMD", "node", "/app/scripts/health-check.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command: sh -c "cd /app && node scripts/run-tests.js && cd frontend && npm run dev -- --host 0.0.0.0"

  # Production environment
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # We'll add the backend service later when needed
  # backend:
  #   build: ./backend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./backend:/app
  #     - /app/node_modules
  #   environment:
  #     - NODE_ENV=development
  #     - DATABASE_URL=postgres://postgres:postgres@db:5432/synthmem
  #   depends_on:
  #     - db

  # db:
  #   image: postgres:14-alpine
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=synthmem

# volumes:
#   postgres_data:
